spring:
  config:
    activate:
      on-profile: test

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: api-service
    serverUrl: ${API_URL:DUMMY-API-URL}
    serverName: Server Test
    title: API Document
    version: 1.0.0